Repository opral/monorepo, pull requests merged in 2024-05, with the labels that each got.

#2715 feat: add message component package
  .changeset/shy-rabbits-love.md
  inlang/source-code/message-component/.storybook/main.js
  inlang/source-code/message-component/.storybook/preview.js
  inlang/source-code/message-component/README.md
  inlang/source-code/message-component/package.json
  inlang/source-code/message-component/src/helper/overridePrimitiveColors.test.ts
  inlang/source-code/message-component/src/helper/overridePrimitiveColors.ts
  inlang/source-code/message-component/src/index.ts
  inlang/source-code/message-component/src/inlang-message.mdx
  inlang/source-code/message-component/src/mock/message.ts
  inlang/source-code/message-component/src/stories/inlang-message.stories.ts
  inlang/source-code/message-component/src/stories/inlang-message.ts
  inlang/source-code/message-component/src/styling/base.ts
  inlang/source-code/message-component/src/styling/preview.css
  inlang/source-code/message-component/tsconfig.json
  pnpm-lock.yaml
Labels: type: feature

#2765 feat: add edit on gh button
  inlang/source-code/website/src/interface/components/doc-layout-solid/doc-layout-meta.tsx
  inlang/source-code/website/src/pages/m/helper/getGithubLink.ts
Labels: type: feature

#2828 feat: fix links in text on landingpage
  inlang/source-code/website/src/pages/index/custom_section/HeroSearch.tsx
Labels: type: bug

#2829 feat: fix z-index
  inlang/source-code/website/src/interface/components/doc-header.tsx
Labels: type: bug

#2830 feat: fix plugin logo fallback in product header
  inlang/source-code/website/src/interface/components/doc-header.tsx
Labels: type: bug

#2831 feat: add lix button on inlang landing page
  inlang/source-code/website/messages/de.json
  inlang/source-code/website/messages/en.json
  inlang/source-code/website/messages/fr.json
  inlang/source-code/website/messages/it.json
  inlang/source-code/website/messages/pt-BR.json
  inlang/source-code/website/messages/sk.json
  inlang/source-code/website/messages/zh.json
  inlang/source-code/website/src/pages/index/custom_section/Lix/index.tsx
Labels: type: feature

#2843 feat: dogfood project counter
  inlang/source-code/website/messages/de.json
  inlang/source-code/website/messages/en.json
  inlang/source-code/website/messages/fr.json
  inlang/source-code/website/messages/it.json
  inlang/source-code/website/messages/pt-BR.json
  inlang/source-code/website/messages/sk.json
  inlang/source-code/website/messages/zh.json
  inlang/source-code/website/src/pages/index/components/CredibilityTag.tsx
Labels: type: feature

#2845 fix: og image for twitter
  inlang/source-code/website/src/pages/documentation/+Page.tsx
Labels: type: bug

#2857 update user numbers on landingpage
  inlang/source-code/website/src/pages/index/+data.ts
Labels: type: improvement

#2793 create mock asts for message bundle component | Message Component
  inlang/source-code/message-bundle-component/package.json
  inlang/source-code/message-bundle-component/src/mock/message.ts
  inlang/source-code/message-bundle-component/src/stories/inlang-message-bundle.stories.ts
  inlang/source-code/message-bundle-component/src/stories/inlang-message-bundle.styles.ts
  inlang/source-code/message-bundle-component/src/stories/inlang-message-bundle.ts
  inlang/source-code/sdk/package.json
  inlang/source-code/sdk/src/v2/helper.test.ts
  inlang/source-code/sdk/src/v2/helper.ts
  inlang/source-code/sdk/src/v2/index.ts
  inlang/source-code/sdk/src/v2/mocks/index.ts
  inlang/source-code/sdk/src/v2/mocks/multipleMatcher/bundle.test.ts
  inlang/source-code/sdk/src/v2/mocks/multipleMatcher/bundle.ts
  inlang/source-code/sdk/src/v2/mocks/plural/bundle.test.ts
  inlang/source-code/sdk/src/v2/mocks/plural/bundle.ts
Labels: type: feature
